trigger:
- master

strategy:
  matrix:
    linux:
      imageName: ubuntu-16.04
    windows:
      imageName: windows-2019

pool:
  vmImage: $(imageName)

steps:
- script: cargo test
  displayName: 'Unit Tests'
